service: redis-refresh
provider:
  runtime: nodejs10.x
  name: aws
  region: us-east-1
  timeout: 60
  environment:
    REDIS_HOST: "bi-cache-server.i1c2dr.ng.0001.use1.cache.amazonaws.com"
    EXPIRE_IN_SECS: "72000"

package:
  exclude:
    - ./**
  include:
    - node_modules/**
    - lib/**

functions:
  refresh:
    handler: lib/index.refresh
